-- Seed data (run by MySQL docker-entrypoint-initdb.d on first init)
-- Objectif: données plus réalistes + images visibles (hero + images inline).
-- IMPORTANT: les fichiers image doivent exister dans /public/uploads/.

-- IMPORTANT (accents) : force l'encodage de la session d'import.
-- Sans ça, l'import docker peut interpréter le fichier en latin1 et produire du mojibake (GenÃ¨ve, Â« ... Â»).
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET character_set_client = utf8mb4;
SET character_set_connection = utf8mb4;
SET character_set_results = utf8mb4;

START TRANSACTION;

SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM article_slug_history;
DELETE FROM articles;
DELETE FROM categories;
DELETE FROM users;
SET FOREIGN_KEY_CHECKS = 1;

-- Admin (login: admin / mdp: admin123)
INSERT INTO users (id, username, password_hash)
VALUES
  (1, 'admin', '$2y$10$W68BCje67nLG9EqCf8tNRuKRgU9N4EuJZFKv2aXlYPuvA00wmj0ay');

-- Catégories (utilisées aussi par la navbar dynamique)
INSERT INTO categories (id, name, slug)
VALUES
  (1, 'Front militaire', 'front-militaire'),
  (2, 'Diplomatie', 'diplomatie'),
  (3, 'Humanitaire', 'humanitaire'),
  (4, 'Économie', 'economie'),
  (5, 'Sécurité', 'securite'),
  (6, 'Analyses', 'analyses');

-- Images attendues (à déposer dans public/uploads/)
-- Chaque article a son image hero unique, et certains ont des images inline uniques.
-- Liste complète des fichiers: public/uploads/IMAGES_A_TELECHARGER.md

INSERT INTO articles (
  id,
  category_id,
  title,
  slug,
  excerpt,
  content_html,
  hero_image_path,
  hero_image_alt,
  meta_title,
  meta_description,
  canonical_url,
  meta_robots,
  status,
  published_at,
  deleted_at
)
VALUES
  (1, 1,
    'Front nord-ouest : repositionnements autour d\'Urmia, les couloirs civils sous pression',
    'front-nord-ouest-repositionnements-urmia',
    'Point de situation sur l\'axe nord-ouest : lignes mouvantes, accès humanitaire, et impacts directs sur les civils. Ce qu\'on peut dire aujourd\'hui, ce qui reste incertain, et les signaux à suivre.',
    '<h2>Résumé de situation</h2><p>Depuis plusieurs jours, des observateurs locaux et des relais humanitaires évoquent des repositionnements successifs sur l\'axe nord-ouest. Le rythme des mouvements et la diversité des sources rendent la vérification difficile : les informations circulent vite, mais toutes ne sont pas confirmées.</p><p>Dans ce contexte, l\'enjeu n\'est pas seulement militaire. Chaque variation de contrôle sur un carrefour, une route secondaire ou un point de passage modifie les itinéraires empruntés par les civils, les ambulances et les convois.</p><figure><img src="/uploads/inline-carte-urmia-axes.webp" alt="Carte de situation (illustration)"><figcaption>Carte de situation (illustration) — positions indicatives.</figcaption></figure><h2>Ce que l\'on peut établir</h2><ul><li><strong>Mouvements graduels</strong> : plutôt que de grandes annonces, la dynamique ressemble à une succession de petites avancées et replis.</li><li><strong>Pression sur les axes</strong> : les routes praticables deviennent un facteur déterminant, notamment pour le ravitaillement et l\'évacuation.</li><li><strong>Information fragmentée</strong> : les récits varient selon les zones et les canaux (témoin, média local, communiqué).</li></ul><h2>Ce qui reste incertain</h2><p>La cartographie précise et l\'étendue réelle des déplacements restent difficiles à confirmer en temps réel. Les images partagées peuvent être anciennes ou sorties de contexte, et les bilans (dégâts, déplacements) fluctuent.</p><h2>Impact civil et logistique</h2><p>Lorsque l\'accès se réduit, l\'effet est immédiat : allongement des temps d\'évacuation, rupture de stocks, et hausse du risque pour les personnes qui tentent de se déplacer.</p><figure><img src="/uploads/inline-logistique-evacuation.webp" alt="Logistique et évacuation (illustration)"><figcaption>Évacuation et logistique (illustration) — l\'accès conditionne les soins.</figcaption></figure><h2>À surveiller (signaux faibles)</h2><ul><li>Changements annoncés sur l\'ouverture/fermeture des points de passage</li><li>Messages officiels sur des « fenêtres » de circulation</li><li>Évolution des alertes locales (sécurité, couvre-feu, contrôles)</li><li>Accès accordé (ou retiré) aux équipes humanitaires</li></ul><h2>Repère de lecture</h2><p>Dans une zone où la vérification est compliquée, la prudence est un indicateur de qualité : distinguer les faits datés et localisés des commentaires, et noter ce qui manque pour conclure.</p>',
    'uploads/hero-front-urmia-repositionnements.webp',
    'Véhicules et fumées au nord-ouest, illustration du front',
    'Front nord-ouest : point de situation autour d\'Urmia',
    'Mouvements tactiques autour d\'Urmia : ce que l\'on sait, ce qui reste incertain et les enjeux humanitaires.',
    NULL,
    'index,follow',
    'published',
    '2026-03-31 08:10:00',
    NULL
  ),
  (2, 2,
    'Genève : reprise d\'un cycle de discussions, calendrier et « mesures de confiance » sur la table',
    'geneve-reprise-discussions-calendrier-mesures-de-confiance',
    'Les délégations évoquent un format en deux temps (technique puis politique) et insistent sur des « mesures de confiance » graduelles. Notre lecture : ce qui est concret, ce qui relève du signal, et les points de friction possibles.',
    '<h2>Ce qui se joue à ce stade</h2><p>La reprise d\'un cycle de discussions ne dit pas tout de l\'issue, mais elle dit beaucoup de la méthode. À Genève, les échanges se concentrent d\'abord sur des éléments praticables : calendrier, mécanismes de vérification, et règles de communication.</p><p>Les formats « allégés » sont fréquents au démarrage : ils permettent d\'avancer sur des sujets techniques sans exposer immédiatement les dirigeants à un risque politique.</p><h2>Format en deux temps : pourquoi</h2><ul><li><strong>Phase technique</strong> : clarifier les termes, définir des étapes vérifiables, et éviter les malentendus.</li><li><strong>Phase politique</strong> : acter (ou non) les compromis et les présenter à l\'opinion.</li></ul><figure><img src="/uploads/inline-salle-negociation-geneve.webp" alt="Salle de négociation (illustration)"><figcaption>Négociations : réunion de travail (illustration).</figcaption></figure><h2>Les « mesures de confiance » : de quoi parle-t-on ?</h2><p>Dans le langage diplomatique, une mesure de confiance est souvent <em>réversible</em>, <em>progressive</em> et <em>vérifiable</em>. L\'objectif est de réduire la méfiance sans demander une concession « irréparable » dès le début.</p><h2>Points sensibles (souvent sous-estimés)</h2><ul><li>Qui vérifie, avec quelles données, et selon quel calendrier ?</li><li>Comment gérer les incidents sans faire dérailler tout le processus ?</li><li>Comment annoncer les étapes sans créer d\'attentes irréalistes ?</li></ul><h2>Ce qui serait un signal concret</h2><p>Un indicateur robuste serait l\'annonce d\'un rendez-vous daté, d\'un document de travail commun et d\'un mécanisme de suivi. À l\'inverse, un flou sur le calendrier ou des formulations trop générales signalent souvent une négociation encore fragile.</p><h2>Ce qu\'on ne peut pas conclure</h2><p>La présence de délégations ne garantit pas un accord. La méthode peut progresser alors que le fond reste bloqué : il faut donc surveiller les éléments vérifiables plutôt que les formules.</p>',
    'uploads/hero-diplomatie-geneve-cycle.webp',
    'Réunion diplomatique, illustration des discussions à Genève',
    'Genève : reprise de discussions et calendrier',
    'Reprise de discussions à Genève : format, calendrier et mesures de confiance évoquées par les délégations.',
    NULL,
    'index,follow',
    'published',
    '2026-03-30 18:35:00',
    NULL
  ),
  (3, 3,
    'Corridor humanitaire : afflux à Kermanshah, les centres de transit saturent',
    'corridor-humanitaire-afflux-kermanshah-centres-transit',
    'Les arrivées se font par vagues et mettent sous tension l\'hébergement d\'urgence, l\'eau et la santé primaire. Les autorités parlent de renforts, les ONG décrivent surtout une contrainte logistique : transporter, trier, orienter, puis recommencer.',
    '<h2>Ce que décrivent les acteurs sur place</h2><p>Les centres de transit autour de Kermanshah reçoivent des arrivées par vagues. Les périodes de calme apparent alternent avec des pics d\'afflux qui saturent l\'accueil, la distribution et l\'orientation.</p><p>À court terme, la capacité se mesure moins au nombre de lits qu\'à la <strong>chaîne complète</strong> : eau, hygiène, soins primaires, information, puis transport vers un lieu plus stable.</p><figure><img src="/uploads/inline-distribution-aide-kermanshah.webp" alt="Distribution d\'aide (illustration)"><figcaption>Distribution d\'aide (illustration) — priorités : eau, soins, triage.</figcaption></figure><h2>Les besoins prioritaires (dans l\'ordre le plus cité)</h2><ul><li><strong>Eau</strong> et points de distribution fiables</li><li><strong>Hygiène</strong> : savon, protections, kits de base</li><li><strong>Santé</strong> : soins primaires, triage, médicaments courants</li><li><strong>Énergie</strong> : recharge, éclairage, conservation de certains produits</li><li><strong>Information</strong> : itinéraires, points de regroupement, procédures</li></ul><h2>Pourquoi la logistique fatigue vite</h2><p>Quand les routes changent, les stocks ne suivent plus : un camion peut mettre deux fois plus de temps, ou ne pas passer du tout. Les équipes doivent alors arbitrer entre <em>tenir un point</em> (stabiliser) et <em>se déplacer</em> (répondre à l\'afflux).</p><h2>Ce qui peut évoluer d\'une heure à l\'autre</h2><p>La situation dépend des ouvertures de routes, des annonces de sécurité locale et de la coordination entre autorités et ONG. La meilleure lecture est souvent de suivre les informations opérationnelles (axes praticables, horaires, points d\'accueil) plutôt que les bilans instantanés.</p><h2>Repère de lecture</h2><p>Un centre de transit « tient » quand la distribution, l\'orientation et les soins primaires restent fluides. Quand ces trois boucles se bloquent en même temps, la saturation se voit immédiatement.</p>',
    'uploads/hero-humanitaire-kermanshah-transit.webp',
    'Civils en transit, illustration d\'un corridor humanitaire',
    'Corridor humanitaire : Kermanshah sous pression',
    'Afflux au corridor de Kermanshah : saturation, besoins prioritaires et contraintes logistiques.',
    NULL,
    'index,follow',
    'published',
    '2026-03-29 07:55:00',
    NULL
  ),
  (4, 4,
    'Marché pétrolier : le Brent réagit aux annonces, comment lire les mouvements',
    'marche-petrolier-brent-reagit-comment-lire-mouvements',
    'Volatilité, prime de risque et effet d\'anticipation : trois clés pour comprendre la réaction du Brent aux annonces. Guide de lecture : ce qu\'un mouvement de prix signifie (souvent) et ce qu\'il ne prouve pas.',
    '<h2>Pourquoi le Brent réagit si vite</h2><p>Le prix ne reflète pas seulement l\'offre et la demande « physiques » du jour. Il reflète surtout les anticipations : risque de rupture, coût du transport, incertitude sur les flux, et comportement des acteurs financiers.</p><p>Quand l\'incertitude monte, une <strong>prime de risque</strong> peut s\'ajouter très rapidement, parfois avant même qu\'un impact concret ne soit visible.</p><figure><img src="/uploads/inline-graph-brent-30j.webp" alt="Graphique du Brent (illustration)"><figcaption>Graphique (illustration) — les variations sont plus lisibles sur une fenêtre de 30 jours.</figcaption></figure><h2>Trois confusions fréquentes</h2><ul><li><strong>Hausse ponctuelle ≠ tendance</strong> : un pic peut être un « choc » court, sans suite durable.</li><li><strong>Annonce ≠ réalité</strong> : une déclaration peut déplacer le prix même si les flux ne changent pas encore.</li><li><strong>Faible liquidité ≠ conviction</strong> : sur certaines séances, quelques ordres suffisent à amplifier un mouvement.</li></ul><h2>Comment lire un graphe en pratique</h2><p>Regarder d\'abord la période : 24h, 7 jours, 30 jours ne racontent pas la même histoire. Puis vérifier la source et la méthode (prix spot, futures, moyenne).</p><h2>À suivre cette semaine (indicateurs simples)</h2><ul><li>Évolution des stocks et révisions de projections</li><li>Flux maritimes et contraintes sur le transport</li><li>Déclarations d\'acteurs clés (production, logistique, assurances)</li></ul><h2>Repère de prudence</h2><p>Un mouvement de prix est un signal, pas une preuve. Pour conclure, il faut le recouper avec des données de flux et de stocks.</p>',
    'uploads/hero-economie-brent-volatilite.webp',
    'Installation énergétique, illustration du marché pétrolier',
    'Marché pétrolier : comprendre les mouvements du Brent',
    'Volatilité du Brent : prime de risque, anticipation et lecture des mouvements sur les graphiques.',
    NULL,
    'index,follow',
    'published',
    '2026-03-28 11:20:00',
    NULL
  ),
  (5, 6,
    'Drones : ce que les images ne montrent pas (et comment éviter les contresens)',
    'drones-ce-que-les-images-ne-montrent-pas',
    'Entre cadrage, compression et contexte manquant, une image peut tromper autant qu\'informer. Méthode simple pour éviter les contresens : dater, localiser, recouper, et formuler des conclusions proportionnées aux preuves.',
    '<h2>Pourquoi une image « convaincante » peut être trompeuse</h2><p>Les images de drones donnent une impression de précision. Pourtant, elles sont souvent partielles : un angle, un moment, une altitude, et parfois une forte compression. Ce que l\'on <em>ne voit pas</em> (avant/après, zone autour, conditions) compte autant que ce que l\'on voit.</p><h2>Le piège du cadrage</h2><p>Une séquence courte peut masquer l\'avant et l\'après. L\'effet « spectaculaire » ne dit pas la cause, ni la chronologie. Une bonne pratique est de chercher des éléments invariants et de reconstituer l\'ordre des événements.</p><h2>Repères utiles pour localiser</h2><ul><li>Éléments fixes : routes, bâtiments, relief, cours d\'eau</li><li>Ombres et orientation (à manier avec prudence)</li><li>Comparaison avec des images de référence (cartes, vues satellite)</li></ul><figure><img src="/uploads/inline-drone-checklist-osint.webp" alt="Analyse d\'image (illustration)"><figcaption>Analyse d\'image (illustration) — une checklist réduit les contresens.</figcaption></figure><h2>Ce qu\'on peut conclure (et ce qu\'on ne peut pas)</h2><p>Une seule image permet parfois de conclure à la présence d\'un objet ou à un type d\'événement. Elle ne permet pas toujours de conclure à l\'intention, au bilan ou à la responsabilité. La formulation doit suivre la force de la preuve.</p><h2>Checklist rapide (2 minutes)</h2><ol><li><strong>Source d\'origine</strong> : qui publie, et d\'où vient le fichier ?</li><li><strong>Date</strong> : première publication, indices de recyclage, incohérences.</li><li><strong>Lieu</strong> : éléments fixes, cohérence avec le relief.</li><li><strong>Recoupement</strong> : au moins une source indépendante ou un indice matériel.</li><li><strong>Conclusion prudente</strong> : décrire avant d\'interpréter.</li></ol><h2>Astuce</h2><p>Quand on n\'a pas assez d\'éléments, le plus utile est de l\'écrire : « non vérifiable », « localisation incertaine », « images partielles ».</p>',
    'uploads/hero-analyses-drones-surveillance.webp',
    'Drone en vol, illustration de surveillance',
    'Drones : comment lire une image sans surinterpréter',
    'Décryptage : comment analyser des images de drones sans contresens (source, date, localisation, recoupement).',
    NULL,
    'index,follow',
    'published',
    '2026-03-27 16:05:00',
    NULL
  ),
  (6, 2,
    'Sanctions : quelles options de négociation sans perdre la face ?',
    'sanctions-options-negociation-sans-perdre-la-face',
    'Panorama des options de méthode : étapes, vérification, clauses de retour et communication. L\'enjeu est souvent moins le principe que la séquence : qui fait quoi, quand, et comment prouver que cela a été fait.',
    '<h2>Pourquoi « perdre la face » est un vrai paramètre</h2><p>Dans une négociation sous tension, une concession peut être techniquement acceptable mais politiquement impossible si elle ressemble à une capitulation. Les équipes cherchent donc des formulations et des étapes qui restent « vendables » en interne.</p><h2>Les positions publiques (et ce qu\'elles cachent parfois)</h2><p>Les déclarations officielles servent à la fois à négocier et à rassurer un public. Elles peuvent donc être plus rigides que les échanges de travail. Lire un discours ne suffit pas : il faut observer la méthode mise en place.</p><h2>Leviers techniques récurrents</h2><ul><li><strong>Vérification</strong> : quelles preuves, par qui, à quelle fréquence ?</li><li><strong>Séquencement</strong> : quelles étapes avant quelles étapes ?</li><li><strong>Clauses de retour</strong> : que se passe-t-il en cas de non-respect ?</li><li><strong>Communication</strong> : comment annoncer sans piéger le processus ?</li></ul><h2>Trois architectures possibles</h2><ol><li><strong>Échanges simultanés</strong> : chaque partie applique une mesure au même moment.</li><li><strong>Étapes conditionnelles</strong> : une mesure déclenche la suivante après vérification.</li><li><strong>Paquets thématiques</strong> : regrouper plusieurs mesures pour équilibrer les coûts politiques.</li></ol><h2>Ce qui change l\'équation</h2><p>Un calendrier clair et un mécanisme de contrôle partagé réduisent l\'incertitude. À l\'inverse, un flou sur la vérification ou sur la réversibilité fragilise le processus : chacun craint d\'être le « seul » à agir.</p><h2>Repère de lecture</h2><p>Quand une négociation progresse, on voit apparaître des éléments concrets : documents de travail, vocabulaire commun, et procédures de suivi.</p>',
    'uploads/hero-diplomatie-sanctions-negociation.webp',
    'Table de négociation, illustration diplomatique',
    'Sanctions : options de négociation',
    'Options de négociation autour des sanctions : étapes, vérification et clauses de retour.',
    NULL,
    'index,follow',
    'published',
    '2026-03-26 09:40:00',
    NULL
  ),
  (7, 5,
    'Sécurité : vérifier une information en 5 minutes (méthode simple)',
    'securite-verifier-information-5-minutes',
    'Une méthode express en 5 minutes : source, date, lieu, recoupement, contexte. Objectif : réduire les erreurs les plus fréquentes (recyclage d\'images, mauvaises localisations, conclusions trop rapides).',
    '<h2>Pourquoi cette méthode suffit souvent</h2><p>Beaucoup de fausses informations ne sont pas sophistiquées : elles reposent sur des images recyclées, des lieux mal attribués, ou des extrapolations. En cinq minutes, on peut déjà éliminer une grande partie des erreurs grossières.</p><h2>1) Identifier la source</h2><p>Officiel, média identifié, témoin, compte anonyme : la valeur n\'est pas la même. Noter le niveau de responsabilité (un communiqué engage davantage qu\'un repost).</p><h2>2) Dater</h2><p>Beaucoup de contenus recyclent d\'anciennes images. Chercher la première publication (reverse image search si besoin) et vérifier si le contexte correspond.</p><h2>3) Localiser</h2><p>Un élément fixe (montagne, carrefour, façade, panneau) peut suffire à invalider une rumeur. Le plus utile est parfois de conclure : « localisation incertaine ».</p><h2>4) Recouper</h2><p>Deux sources indépendantes valent mieux qu\'une chaîne de reposts. Recouper ne signifie pas « dix comptes qui se copient ».</p><h2>5) Remettre en contexte</h2><p>Éviter de tirer une conclusion globale d\'un incident isolé. Noter ce qui manque : lieu exact, date, acteurs, suite.</p><h2>Mini-grille (à copier)</h2><ul><li><strong>Fait</strong> : ce qui est montré / dit</li><li><strong>Preuve</strong> : image, document, témoignage</li><li><strong>Degré</strong> : confirmé / probable / non vérifié</li><li><strong>Manque</strong> : ce qu\'il faut pour conclure</li></ul>',
    'uploads/hero-securite-verification-5-min.webp',
    'Véhicules sur une route, illustration de contexte sécuritaire',
    'Sécurité : vérifier une info en 5 minutes',
    'Méthode simple pour vérifier une information : source, date, lieu, recoupement, contexte.',
    NULL,
    'index,follow',
    'published',
    '2026-03-25 07:10:00',
    NULL
  ),
  (8, 4,
    'Budget : trois scénarios pour expliquer l\'incertitude (base, prudent, risque)',
    'budget-trois-scenarios-base-prudent-risque',
    'Un modèle simple pour raconter l\'incertitude sans noyer le lecteur : trois scénarios (base, prudent, risque) sur quelques indicateurs identiques. Utile pour expliquer « ce qui pourrait changer » plutôt que de prédire.',
    '<h2>Pourquoi parler en scénarios</h2><p>Quand l\'incertitude est forte, donner un seul chiffre donne une fausse impression de précision. Les scénarios servent à encadrer le possible : ce qui se tient si les hypothèses restent stables, et ce qui arrive si elles se dégradent.</p><h2>Les 3 scénarios (version pédagogique)</h2><h3>1) Scénario de base</h3><p>Hypothèses globalement stables : pas de choc majeur sur les flux, ajustements limités, trajectoire « moyenne ».</p><h3>2) Scénario prudent</h3><p>Hypothèses plus conservatrices : recettes sous pression, demande plus faible, délais logistiques plus longs.</p><h3>3) Scénario risque</h3><p>Choc externe et contraintes durables : ruptures, incertitude persistante, coûts de transport et d\'assurance plus élevés.</p><h2>Comment comparer sans se perdre</h2><ul><li>Choisir <strong>2–3 indicateurs</strong> identiques pour tous les scénarios (prix, flux, délais).</li><li>Écrire <strong>les hypothèses</strong> en une phrase par scénario (ce qui change).</li><li>Mettre l\'accent sur <strong>les ordres de grandeur</strong>, pas sur le décimal.</li></ul><h2>Astuce rédaction</h2><p>Une phrase utile par scénario : « Si X se produit, alors Y devient probable ». Cela rend la lecture plus concrète et plus honnête.</p>',
    'uploads/hero-economie-budget-scenarios.webp',
    'Graphiques économiques, illustration budgétaire',
    'Budget : trois scénarios simples',
    'Trois scénarios (base, prudent, risque) pour expliquer l\'incertitude économique liée au conflit.',
    NULL,
    'index,follow',
    'published',
    '2026-03-24 10:00:00',
    NULL
  ),
  (9, 3,
    'Triage médical : comment les équipes priorisent quand tout manque',
    'triage-medical-comment-prioriser-quand-tout-manque',
    'Quand les ressources manquent, le triage sert à sauver le plus de vies possible avec des moyens limités. Ce n\'est pas un jugement sur les personnes, mais une procédure : évaluer vite, orienter, stabiliser, et documenter.',
    '<h2>Ce qu\'est le triage (et ce que ce n\'est pas)</h2><p>Le triage vise à orienter rapidement les soins vers les cas où l\'intervention change le pronostic. Il ne remplace pas la prise en charge : il organise les priorités quand tout arrive en même temps.</p><p>En situation de crise, les équipes cherchent à réduire deux risques : <strong>perdre du temps</strong> sur des gestes peu efficaces et <strong>manquer</strong> les cas qui peuvent être sauvés avec une intervention rapide.</p><figure><img src="/uploads/inline-poste-medical-triage.webp" alt="Poste médical avancé (illustration)"><figcaption>Poste médical avancé (illustration) — priorité à l\'évaluation rapide.</figcaption></figure><h2>La boucle opérationnelle</h2><ol><li><strong>Évaluer</strong> : état général, respiration, hémorragie, conscience.</li><li><strong>Catégoriser</strong> : urgence immédiate, différable, mineur, attente.</li><li><strong>Orienter</strong> : zone de soins, évacuation, réévaluation.</li><li><strong>Réévaluer</strong> : les catégories changent avec le temps.</li></ol><h2>Pourquoi l\'hygiène compte autant</h2><p>Les infections et les complications augmentent quand l\'eau, le lavage des mains et les consommables manquent. Un kit d\'urgence (hygiène + premiers soins) a souvent un impact disproportionné sur la capacité d\'un poste à tenir.</p><figure><img src="/uploads/inline-kits-hygiene.webp" alt="Kits d\'urgence (illustration)"><figcaption>Kits d\'urgence (illustration) — hygiène et premiers soins.</figcaption></figure><h2>Ce qui aide concrètement les équipes</h2><ul><li><strong>Itinéraires sûrs et réguliers</strong> : évacuer sans improviser</li><li><strong>Stocks de base</strong> : pansements, antalgiques, eau, gants</li><li><strong>Communication</strong> : expliquer la procédure aux familles</li><li><strong>Documentation</strong> : tracer les décisions et les transferts</li></ul><h2>Repère de lecture</h2><p>Un poste médical « tient » quand l\'orientation reste fluide et que la réévaluation est possible. Quand la logistique se bloque, le triage devient plus difficile et plus dur à expliquer.</p>',
    'uploads/hero-humanitaire-triage-medical.webp',
    'Centre de transit et aide, illustration humanitaire',
    'Triage médical : comprendre la priorisation',
    'Triage médical : principes, contraintes et ce qui peut améliorer la prise en charge en contexte de crise.',
    NULL,
    'index,follow',
    'published',
    '2026-03-23 15:25:00',
    NULL
  ),
  (10, 6,
    'Chronologie : les annonces publiques qui ont changé le ton du mois',
    'chronologie-annonces-publiques-qui-ont-change-le-ton',
    'Une chronologie plus détaillée pour replacer annonces, démentis et signaux dans l\'ordre. Objectif : éviter les contresens (comparer des déclarations qui ne répondent pas à la même question, ni au même public).',
    '<h2>Pourquoi une chronologie est utile</h2><p>Dans une période intense, les déclarations s\'enchaînent : annonces, rectificatifs, « précisions », et parfois contradictions. Sans chronologie, on finit par comparer des phrases prononcées dans des contextes différents.</p><h2>Comment nous la lisons</h2><p>Deux critères sont souvent plus informatifs que le contenu brut : <strong>le timing</strong> (quand c\'est dit) et <strong>le canal</strong> (où et à qui c\'est dit). Une fuite, un communiqué, une conférence de presse n\'ont pas la même fonction.</p><h2>Repères du mois (version pédagogique)</h2><ul><li><strong>Semaine 1</strong> : annonces et premières réactions — montée du bruit informationnel.</li><li><strong>Semaine 2</strong> : ajustements — correction de formulations, changement d\'accent.</li><li><strong>Semaine 3</strong> : signaux de méthode — insistance sur procédures, vérification, calendrier.</li><li><strong>Semaine 4</strong> : stabilisation relative — messages plus cohérents, vocabulaire plus répété.</li></ul><h2>Ce qu\'on retient (règles simples)</h2><ol><li>Un message répété sur plusieurs canaux est souvent plus solide qu\'une phrase isolée.</li><li>Un changement de vocabulaire (de « ferme » à « technique ») est un signal.</li><li>Les démentis sont parfois aussi importants que les annonces.</li></ol><h2>Limites</h2><p>Une chronologie ne prouve pas une intention. Elle sert surtout à réduire les contresens et à repérer les moments où la communication change.</p>',
    'uploads/hero-analyses-chronologie-annonces.webp',
    'Microphones et pupitre, illustration de communication officielle',
    'Chronologie : annonces publiques du mois',
    'Chronologie des annonces publiques : repères et lecture du timing des communications.',
    NULL,
    'index,follow',
    'published',
    '2026-03-22 08:45:00',
    NULL
  ),
  (11, 1,
    'Logistique : pourquoi une route vaut parfois un front',
    'logistique-pourquoi-une-route-vaut-parfois-un-front',
    'Ravitaillement, carburant, temps de trajet : une contrainte logistique peut dominer une décision tactique. Décryptage : pourquoi une route (ou un carrefour) peut compter autant qu\'une ligne de front.',
    '<h2>La logistique, c\'est le temps</h2><p>Dans une zone tendue, la question n\'est pas seulement « qui contrôle » mais « qui peut <em>tenir</em> ». Tenir suppose de ravitailler : carburant, nourriture, eau, munitions, et surtout <strong>temps de trajet</strong> acceptable.</p><h2>Ce qu\'une route fermée change immédiatement</h2><p>Une route fermée peut transformer une zone en impasse logistique, même sans combat direct. Les itinéraires deviennent plus longs, plus risqués, parfois impraticables.</p><figure><img src="/uploads/inline-carte-itineraires-logistiques.webp" alt="Itinéraires logistiques (illustration)"><figcaption>Itinéraires (illustration) — l\'accès conditionne l\'évacuation et les soins.</figcaption></figure><h2>Effets visibles (côté civil et humanitaire)</h2><ul><li><strong>Rupture de carburant</strong> : moins de mobilité, générateurs à l\'arrêt, chaînes du froid fragilisées.</li><li><strong>Délais médicaux</strong> : évacuations plus longues, triage plus dur, saturations.</li><li><strong>Stocks instables</strong> : difficulté à maintenir des consommables (eau, hygiène, médicaments).</li><li><strong>Information</strong> : rumeurs sur les routes « ouvertes » qui changent trop vite.</li></ul><h2>Pourquoi ça pèse sur les décisions</h2><p>Quand un acteur perd un axe, il perd souvent de la flexibilité : il doit concentrer ses moyens sur la protection d\'un détour ou d\'un passage unique. C\'est pour cela qu\'un carrefour peut devenir un objectif stratégique.</p><h2>Repère de lecture</h2><p>Si les temps de trajet doublent et que les stocks deviennent irréguliers, la logistique devient le facteur dominant — et la situation peut changer sans annonce spectaculaire.</p>',
    'uploads/hero-front-logistique-routes.webp',
    'Route et convoi, illustration logistique',
    'Logistique : la route comme enjeu',
    'Logistique en zone de conflit : comment les routes et délais influencent les décisions et l\'humanitaire.',
    NULL,
    'index,follow',
    'published',
    '2026-03-21 12:05:00',
    NULL
  ),
  (12, 4,
    'Guide : lire un graphique économique sans se faire piéger',
    'guide-lire-graphique-economique-sans-piege',
    'Axes, période, source, et ce qu\'on peut (ou non) conclure. Un guide de lecture pour éviter les pièges classiques : échelle trompeuse, fenêtre trop courte, et conclusions qui dépassent les données.',
    '<h2>Pourquoi on se fait piéger</h2><p>Un graphique donne une impression de neutralité. Pourtant, une simple décision (échelle, période, type de moyenne) peut changer la perception. L\'objectif n\'est pas de « se méfier de tout », mais de poser trois questions systématiques.</p><h2>1) Les axes</h2><p>Vérifier unités, échelle et éventuelle rupture d\'axe. Une échelle compressée peut « lisser » une crise, une échelle tronquée peut dramatiser une variation.</p><h2>2) La période</h2><p>Une variation sur 24h n\'a pas la même signification que sur 30 jours. Plus la période est courte, plus le bruit est important.</p><figure><img src="/uploads/inline-lecture-graphique-axes-periode.webp" alt="Lecture de graphique (illustration)"><figcaption>Lecture de graphique (illustration) — regarder la source et la période.</figcaption></figure><h2>3) La source</h2><p>Identifier la source permet d\'évaluer la qualité : méthode, fréquence, corrections, et éventuels changements de définition.</p><h2>Ce qu\'on peut conclure (en général)</h2><ul><li>La direction sur une période donnée (hausse/baisse)</li><li>La volatilité (stabilité vs variations rapides)</li><li>Les ruptures (changement de régime)</li></ul><h2>Ce qu\'on doit éviter</h2><ul><li>Conclure à une cause unique sans recouper</li><li>Extrapoler une journée à un mois</li><li>Comparer des séries non comparables (définitions différentes)</li></ul><h2>Phrase utile</h2><p>« Le graphique montre X sur la période Y, mais ne dit pas à lui seul pourquoi. »</p>',
    'uploads/hero-economie-guide-graphique.webp',
    'Graphique de marché, illustration',
    'Guide : lire un graphique économique',
    'Guide pratique pour lire un graphique : axes, période, source, et limites de l\'interprétation.',
    NULL,
    'index,follow',
    'published',
    '2026-03-20 09:15:00',
    NULL
  ),
  (13, 2,
    'Entretien : comment lire les signaux diplomatiques (mots, timing, canaux)',
    'entretien-lire-signaux-diplomatiques-mots-timing-canaux',
    'Une grille de lecture simple pour analyser une déclaration sans surinterpréter : mots, timing, canaux, et cohérence avec les actes. L\'idée : distinguer le signal (communication) du changement concret (méthode, calendrier, documents).',
    '<h2>Pourquoi les signaux sont difficiles à lire</h2><p>En diplomatie, une phrase est souvent écrite pour plusieurs publics : interlocuteur, opinion interne, partenaires, médias. Cela produit un langage codé, où certains mots sont choisis pour <em>laisser de la marge</em>.</p><h2>1) Mots et formules</h2><p>Des termes comme « constructif », « substantiel », « technique », « franc » servent souvent à cadrer l\'attente. Un mot peut marquer une ouverture, mais peut aussi être un simple élément de style.</p><p><strong>Astuce</strong> : noter les mots nouveaux (apparition) et les mots qui disparaissent (abandon).</p><h2>2) Timing</h2><p>Le moment d\'une annonce peut indiquer une intention : calmer, accélérer, déplacer le débat, ou préparer un rendez-vous. Un message envoyé juste avant une réunion n\'a pas le même rôle qu\'un message après.</p><h2>3) Canaux</h2><p>Communiqué, conférence, fuite : chaque canal vise un public différent. Une fuite peut tester une idée sans engager officiellement, une conférence peut « verrouiller » un récit.</p><h2>4) Cohérence avec les actes</h2><p>Le signal devient plus solide quand il s\'accompagne d\'actes : calendrier, groupe de travail, texte commun, mécanisme de suivi.</p><h2>Conclusion prudente</h2><p>On peut décrire le signal (ton, vocabulaire, canal). On doit être plus prudent sur l\'interprétation (intention). La méthode (ce qui est mis en place) est souvent plus informative que la phrase.</p>',
    'uploads/hero-diplomatie-entretien-signaux.webp',
    'Salle de presse, illustration',
    'Entretien : lire les signaux diplomatiques',
    'Grille de lecture : mots, timing et canaux pour interpréter les signaux diplomatiques.',
    NULL,
    'index,follow',
    'published',
    '2026-03-19 14:20:00',
    NULL
  ),
  (14, 5,
    'Questions fréquentes : “confirmé”, “en cours”, “source locale” — ce que ça veut dire',
    'questions-frequentes-confirme-en-cours-source-locale',
    'Petit lexique pour mieux comprendre les niveaux de certitude dans les dépêches. Objectif : lire plus finement une info sans tomber dans « vrai/faux » immédiat, surtout quand les détails évoluent.',
    '<h2>Pourquoi le vocabulaire compte</h2><p>Dans une situation fluide, deux articles peuvent parler du même événement avec des mots différents. Ces mots indiquent souvent le niveau de vérification et la stabilité des informations.</p><h2>« Confirmé »</h2><p>En principe : information recoupée par plusieurs sources indépendantes, ou validée par une source engagée (ex. communiqué officiel). Attention : « confirmé » peut aussi être utilisé de manière abusive sur les réseaux.</p><p><strong>À demander</strong> : confirmé par qui ? avec quelles preuves ?</p><h2>« En cours »</h2><p>Événement non stabilisé : le bilan et les détails peuvent évoluer. C\'est souvent le mot juste quand la situation est active.</p><p><strong>À retenir</strong> : « en cours » implique une mise à jour probable.</p><h2>« Source locale »</h2><p>Peut désigner des témoins, des autorités locales ou des médias régionaux. Cela peut être utile, mais c\'est trop vague si on ne précise pas.</p><p><strong>À demander</strong> : témoin direct ? média identifié ? autorité locale ?</p><h2>Autres termes utiles</h2><ul><li><strong>« Selon »</strong> : information rapportée, pas forcément validée.</li><li><strong>« Non vérifié »</strong> : honnêteté sur les limites.</li><li><strong>« Démenti »</strong> : ne prouve pas l\'inverse, mais change le niveau de prudence.</li></ul><h2>Conseil</h2><p>Garder un vocabulaire prudent quand les éléments sont partiels et distinguer <em>ce qui est décrit</em> de <em>ce qui est interprété</em>.</p>',
    'uploads/hero-securite-lexique-certitude.webp',
    'Bloc-notes et radio, illustration',
    'FAQ : niveaux de certitude des informations',
    'Lexique des niveaux de certitude : confirmé, en cours, source locale — comment lire une dépêche.',
    NULL,
    'index,follow',
    'published',
    '2026-03-18 08:00:00',
    NULL
  ),
  (15, 6,
    'Guide rédaction : structurer un article factuel (H2, sources, SEO) — modèle prêt',
    'guide-redaction-article-factuel-modele',
    'Une structure simple et réutilisable pour rendre la lecture claire et “SEO-friendly”. Modèle prêt : sections H2, vocabulaire prudent, encadrés « ce qu\'on sait / ce qu\'on ne sait pas », et check-list de publication.',
    '<h2>Objectif : clarté + honnêteté</h2><p>Un article factuel n\'est pas forcément long : il est surtout clair sur ce qui est établi, ce qui est rapporté et ce qui est incertain. Une bonne structure aide à éviter les contresens.</p><h2>Structure (modèle)</h2><ol><li><strong>Chapeau</strong> : 2–3 phrases qui répondent à « quoi, où, quand ».</li><li><strong>Contexte (H2)</strong> : pourquoi on en parle, sans réécrire toute l\'histoire.</li><li><strong>Faits (H2)</strong> : ce qui est établi, daté et localisé.</li><li><strong>Impacts (H2)</strong> : conséquences concrètes (civils, logistique, économie).</li><li><strong>Ce qui manque (H2)</strong> : éléments nécessaires pour conclure.</li><li><strong>Suite (H2)</strong> : ce qu\'on surveille, prochaines annonces, scénarios.</li></ol><h2>Sources (bonnes pratiques)</h2><ul><li>Séparer <strong>source</strong> et <strong>interprétation</strong>.</li><li>Indiquer le <strong>niveau</strong> : confirmé / probable / non vérifié.</li><li>Éviter la « chaîne de reposts » : chercher l\'origine.</li></ul><h2>SEO (sans tricher)</h2><p>Le SEO sert d\'abord à aider le lecteur : meta title descriptif, meta description utile, et un slug propre. Éviter le bourrage de mots-clés.</p><h2>Checklist publication</h2><ul><li>Le chapeau répond-il à « quoi/où/quand » ?</li><li>Les faits sont-ils datés et localisés ?</li><li>Les limites sont-elles écrites clairement ?</li><li>Le titre et le slug sont-ils cohérents ?</li></ul>',
    'uploads/hero-analyses-guide-redaction.webp',
    'Écran de rédaction, illustration',
    'Guide : rédiger un article factuel',
    'Conseils de rédaction : structure H2, sources et SEO (meta title/description) pour un article factuel.',
    NULL,
    'index,follow',
    'published',
    '2026-03-17 10:30:00',
    NULL
  ),
  (16, 1,
    'À compléter : brief du matin (brouillon)',
    'a-completer-brief-du-matin-brouillon',
    'Brouillon interne — non publié.',
    '<h2>Brouillon</h2><p>À compléter par la rédaction : vérifications, chiffres, citations.</p>',
    'uploads/hero-front-brief-matin.webp',
    'Illustration front',
    NULL,
    NULL,
    NULL,
    'noindex,nofollow',
    'draft',
    NULL,
    NULL
  ),
  (17, 3,
    'À compléter : note logistique ONG (brouillon)',
    'a-completer-note-logistique-ong-brouillon',
    'Brouillon interne — non publié.',
    '<h2>Brouillon</h2><p>À compléter : volumes, itinéraires, points de blocage.</p>',
    'uploads/hero-humanitaire-note-ong.webp',
    'Illustration humanitaire',
    NULL,
    NULL,
    NULL,
    'noindex,nofollow',
    'draft',
    NULL,
    NULL
  );

COMMIT;
