-- Seed data (run by MySQL docker-entrypoint-initdb.d on first init)

INSERT INTO users (username, password_hash)
VALUES
  ('admin1', '$2y$10$W68BCje67nLG9EqCf8tNRuKRgU9N4EuJZFKv2aXlYPuvA00wmj0ay'),
  ('admin2', '$2y$10$f/W1UdUW4qP3ui/Bc0mak.xvW3upZJRdztPfLaEq4oDXpOjIRV0oi');

INSERT INTO categories (id, name, slug)
VALUES
  (1, 'Diplomatie', 'diplomatie'),
  (2, 'Economie', 'economie'),
  (3, 'Securite', 'securite');

INSERT INTO articles (
  id,
  category_id,
  title,
  slug,
  excerpt,
  content_html,
  hero_image_path,
  hero_image_alt,
  meta_title,
  meta_description,
  canonical_url,
  meta_robots,
  status,
  published_at,
  deleted_at
)
VALUES
  (1, 1,
    'Iran: nouvelle sequence de negociations',
    'iran-nouvelle-sequence-de-negociations',
    'Resume des derniers echanges diplomatiques et des prochaines etapes annoncees.',
    '<h2>Contexte</h2><p>Une nouvelle sequence de discussions a ete annoncee. Les delegations ont evoque des points de calendrier et de methode.</p><h2>Ce qui change</h2><p>Les parties cherchent a stabiliser un cadre dechange. Des propositions techniques seront etudiees.</p><h2>A surveiller</h2><p>La date du prochain cycle et les signaux publics.</p>',
    NULL,
    NULL,
    'Iran: nouvelle sequence de negociations',
    'Resume des derniers echanges diplomatiques et des prochaines etapes annoncees.',
    NULL,
    'index,follow',
    'published',
    '2026-03-01 09:00:00',
    NULL
  ),
  (2, 1,
    'Sanctions: quelles options diplomatiques?',
    'sanctions-quelles-options-diplomatiques',
    'Panorama des positions et des leviers de negociation autour des sanctions.',
    '<h2>Positions</h2><p>Les acteurs avancent des arguments differents selon leurs priorites politiques.</p><h2>Leviers</h2><p>Plusieurs leviers sont cites: calendrier, verifications, clauses de retour.</p><h2>Impact</h2><p>Les annonces influencent leconomie et la perception des risques.</p>',
    NULL,
    NULL,
    'Sanctions: options diplomatiques',
    'Panorama des positions et des leviers de negociation autour des sanctions.',
    NULL,
    'index,follow',
    'published',
    '2026-03-03 10:30:00',
    NULL
  ),
  (3, 1,
    'Chronologie des communiques officiels',
    'chronologie-des-communiques-officiels',
    'Une chronologie simple pour situer les annonces et les reactions.',
    '<h2>Pourquoi une chronologie</h2><p>Elle permet de comprendre la sequence des annonces.</p><h2>Faits saillants</h2><ul><li>Annonce A</li><li>Reaction B</li><li>Nouvelle etape C</li></ul><h2>Sources</h2><p>Communiques, declarations publiques, points presse.</p>',
    NULL,
    NULL,
    'Chronologie des communiques officiels',
    'Une chronologie simple pour situer les annonces et les reactions.',
    NULL,
    'index,follow',
    'published',
    '2026-03-05 08:15:00',
    NULL
  ),
  (4, 1,
    'Entretien: comment lire les signaux diplomatiques',
    'entretien-comment-lire-les-signaux-diplomatiques',
    'Une grille de lecture: mots, timing, canaux et niveau de representation.',
    '<h2>Mots et formules</h2><p>Les mots choisis comptent: ils peuvent signaler une ouverture ou une ligne rouge.</p><h2>Timing</h2><p>Le moment deune annonce est souvent aussi important que son contenu.</p><h2>Canaux</h2><p>Officiel, officieux, fuite: chaque canal a ses codes.</p>',
    NULL,
    NULL,
    'Entretien: lire les signaux diplomatiques',
    'Une grille de lecture pour mieux comprendre les annonces diplomatiques.',
    NULL,
    'index,follow',
    'published',
    '2026-03-07 12:00:00',
    NULL
  ),
  (5, 1,
    'Q&A: lexique de la diplomatie (simple)',
    'qa-lexique-de-la-diplomatie-simple',
    'Definitions courtes pour comprendre les termes frequents dans les articles.',
    '<h2>Lexique</h2><p><strong>Accord-cadre</strong>: un accord qui fixe les principes.</p><p><strong>Verification</strong>: mecanismes pour controler leapplication.</p><p><strong>Calendrier</strong>: etapes et dates.</p><h2>Conseil</h2><p>Garder une definition courte aide la lisibilite.</p>',
    NULL,
    NULL,
    'Q&A: lexique diplomatie',
    'Definitions courtes pour comprendre les termes frequents.',
    NULL,
    'index,follow',
    'published',
    '2026-03-09 14:20:00',
    NULL
  ),

  (6, 2,
    'Economie: effets visibles sur les prix',
    'economie-effets-visibles-sur-les-prix',
    'Des indicateurs simples pour suivre leevolution des prix et des tensions.',
    '<h2>Indicateurs</h2><p>Suivre un petit nombre deindicateurs rend leanalyse plus claire.</p><h2>Ce que cela signifie</h2><p>Les variations de prix affectent menages et entreprises.</p><h2>Limites</h2><p>Les chiffres doivent etre compares sur la duree.</p>',
    NULL,
    NULL,
    'Economie: effets sur les prix',
    'Indicateurs simples pour suivre leevolution des prix et des tensions.',
    NULL,
    'index,follow',
    'published',
    '2026-03-02 09:10:00',
    NULL
  ),
  (7, 2,
    'Marche: pourquoi la volatilite augmente',
    'marche-pourquoi-la-volatilite-augmente',
    'Explication courte des facteurs de volatilite (risque, liquidite, annonces).',
    '<h2>Risque</h2><p>Les annonces augmentent leincertitude, donc la volatilite.</p><h2>Liquidite</h2><p>Quand la liquidite baisse, les mouvements sont plus amples.</p><h2>Reactions</h2><p>Les marches reagissent vite aux signaux publics.</p>',
    NULL,
    NULL,
    'Marche: volatilite en hausse',
    'Facteurs de volatilite: risque, liquidite et annonces.',
    NULL,
    'index,follow',
    'published',
    '2026-03-04 11:05:00',
    NULL
  ),
  (8, 2,
    'Budget: trois scenarios simples',
    'budget-trois-scenarios-simples',
    'Trois scenarios pour comprendre leincertitude: base, prudent, risque.',
    '<h2>Scenario de base</h2><p>Hypotheses stables et croissance moderee.</p><h2>Scenario prudent</h2><p>Hypotheses plus conservatrices sur les recettes.</p><h2>Scenario risque</h2><p>Chocs externes et contraintes plus fortes.</p>',
    NULL,
    NULL,
    'Budget: trois scenarios',
    'Trois scenarios (base, prudent, risque) pour comprendre leincertitude.',
    NULL,
    'index,follow',
    'published',
    '2026-03-06 08:40:00',
    NULL
  ),
  (9, 2,
    'Energie: points-cles pour comprendre',
    'energie-points-cles-pour-comprendre',
    'Rappels sur leenergie: production, transport, prix et attentes des acteurs.',
    '<h2>Production</h2><p>La production conditionne leoffre et les prix.</p><h2>Transport</h2><p>Les routes et contraintes logistiques comptent.</p><h2>Prix</h2><p>Les prix reagissent aux annonces et aux anticipations.</p>',
    NULL,
    NULL,
    'Energie: points cles',
    'Production, transport, prix: points cles pour comprendre.',
    NULL,
    'index,follow',
    'published',
    '2026-03-08 16:00:00',
    NULL
  ),
  (10, 2,
    'Guide: lire un graphique economique',
    'guide-lire-un-graphique-economique',
    'Un guide court: axes, periode, source, et ce queon peut conclure.',
    '<h2>Axes</h2><p>Verifier les axes et les unites.</p><h2>Periode</h2><p>Regarder la fenetre temporelle pour eviter de tirer des conclusions trop vite.</p><h2>Source</h2><p>Identifier la source pour evaluer la fiabilite.</p>',
    NULL,
    NULL,
    'Guide: lire un graphique economique',
    'Axes, periode, source: guide pour lire un graphique economique.',
    NULL,
    'index,follow',
    'published',
    '2026-03-10 10:00:00',
    NULL
  ),

  (11, 3,
    'Securite: points de situation (resume)',
    'securite-points-de-situation-resume',
    'Resume factuel des elements de contexte securitaire et des annonces recentes.',
    '<h2>Faits</h2><p>Les informations sont presentees de facon factuelle, avec prudence.</p><h2>Zones concernees</h2><p>Plusieurs zones peuvent etre concernees selon les sources.</p><h2>Prudence</h2><p>Recouper les informations avant de conclure.</p>',
    NULL,
    NULL,
    'Securite: points de situation',
    'Resume factuel du contexte securitaire et des annonces recentes.',
    NULL,
    'index,follow',
    'published',
    '2026-03-01 18:00:00',
    NULL
  ),
  (12, 3,
    'Defense: comment verifier une information',
    'defense-comment-verifier-une-information',
    'Methodes simples: source, recoupement, date, localisation, contexte.',
    '<h2>Source</h2><p>Identifier leorigine: officiel, media, temoignage.</p><h2>Recoupement</h2><p>Croiser au moins deux sources independantes.</p><h2>Contexte</h2><p>Eviter de sortir une citation de son contexte.</p>',
    NULL,
    NULL,
    'Defense: verifier une information',
    'Source, recoupement, date: methodes simples pour verifier une information.',
    NULL,
    'index,follow',
    'published',
    '2026-03-03 07:30:00',
    NULL
  ),
  (13, 3,
    'Analyse: vocabulaire securitaire a connaitre',
    'analyse-vocabulaire-securitaire-a-connaitre',
    'Mini lexique des termes frequents dans les articles securite.',
    '<h2>Lexique</h2><p><strong>Escalade</strong>: hausse des tensions.</p><p><strong>De-escalade</strong>: baisse des tensions.</p><p><strong>Incident</strong>: evenement ponctuel.</p><h2>Pourquoi</h2><p>Comprendre le vocabulaire aide la lecture.</p>',
    NULL,
    NULL,
    'Analyse: vocabulaire securitaire',
    'Mini lexique des termes frequents en securite.',
    NULL,
    'index,follow',
    'published',
    '2026-03-05 13:00:00',
    NULL
  ),
  (14, 3,
    'Securite: questions frequentes',
    'securite-questions-frequentes',
    'Reponses courtes aux questions qui reviennent souvent dans les cours et articles.',
    '<h2>Q1</h2><p>Que signifie einformation confirmeeee ?</p><p>Ceest une information recoupee par plusieurs sources.</p><h2>Q2</h2><p>Pourquoi certaines informations changent?</p><p>Parce que les contextes evoluent.</p>',
    NULL,
    NULL,
    'Securite: questions frequentes',
    'Reponses courtes aux questions frequentes en securite.',
    NULL,
    'index,follow',
    'published',
    '2026-03-07 09:45:00',
    NULL
  ),
  (15, 3,
    'Guide: rediger un article factuel',
    'guide-rediger-un-article-factuel',
    'Conseils de redaction: faits, sources, titres, et structure H2/H3.',
    '<h2>Structure</h2><p>Un H1 (le titre), puis H2 pour les sections principales.</p><h2>Sources</h2><p>Citer les sources et separer fait/opinion.</p><h2>SEO</h2><p>Un meta title clair et une meta description utile.</p>',
    NULL,
    NULL,
    'Guide: rediger un article factuel',
    'Conseils: faits, sources, titres et structure H2/H3 pour un article factuel.',
    NULL,
    'index,follow',
    'published',
    '2026-03-09 08:00:00',
    NULL
  );
